
// Generated by https://quicktype.io

export interface Quote {
    isShared:    boolean;
    _id:         string;
    quote:       string;
    language:    string;
    isPublished: boolean;
    keyWords:    string[];
    user:        string;
    __v:         number;
    author?:     Author;
}

export interface Author {
    name: string;
    id:   string;
}
